{
 "title": "Branch Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "database_branch",
    "label": "Branch",
    "query": {
     "query": "label_values(planetscale_vtgate_total_pods,planetscale_database_branch_id)"
    }
   },
   {
    "name": "planetscale_keyspace",
    "label": "Keyspace",
    "query": {
     "query": "label_values(planetscale_vttablet_connection_pool_capacity{planetscale_database_branch_id=\"$database_branch\"},planetscale_keyspace)"
    }
   },
   {
    "name": "planetscale_shard",
    "label": "Shard",
    "query": {
     "query": "label_values(planetscale_vttablet_connection_pool_capacity{planetscale_database_branch_id=\"$database_branch\", planetscale_keyspace=~\"$planetscale_keyspace\"},planetscale_shard)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Branch Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Incoming Queries by Plan",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_vtgate_commands_count{planetscale_database_branch_id='$database_branch'}[$__rate_interval])) by (planetscale_command)",
     "legendFormat": "{{planetscale_command}}"
    }
   ]
  },
  {
   "title": "Errors by Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_vtgate_errors_count{planetscale_database_branch_id='$database_branch'}[$__rate_interval])) by (planetscale_vtgate_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Usage - Primaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Primary CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "planetscale_pods_cpu_util_percentages{planetscale_database_branch_id='$database_branch', planetscale_component=\"vttablet\", planetscale_tablet_type=\"primary\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}} - {{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Primary Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "planetscale_pods_mem_util_percentages{planetscale_database_branch_id='$database_branch', planetscale_component=\"vttablet\", planetscale_tablet_type=\"primary\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}} - {{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Primary IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum (rate(planetscale_pods_iops_total{planetscale_database_branch_id='$database_branch', planetscale_tablet_type=\"primary\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace, planetscale_shard, planetscale_pod)",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}} - {{planetscale_pod}}"
    }
   ]
  },
  { "title": "Resource Usage - Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Replica CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "planetscale_pods_cpu_util_percentages{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard', planetscale_component=\"vttablet\", planetscale_tablet_type=~\"(replica|rdonly)\"}",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}} - {{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Replica Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "planetscale_pods_mem_util_percentages{planetscale_database_branch_id='$database_branch', planetscale_component=\"vttablet\", planetscale_tablet_type=~\"(replica|rdonly)\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}} - {{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Replica IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_pods_iops_total{planetscale_database_branch_id='$database_branch', planetscale_tablet_type=~\"(replica|rdonly)\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace, planetscale_shard, planetscale_pod)",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}} - {{planetscale_pod}}"
    }
   ]
  },
  { "title": "Resource Usage - VTGate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "VTGate CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "planetscale_pods_cpu_util_percentages{planetscale_database_branch_id='$database_branch', planetscale_component=\"vtgate\"}",
     "legendFormat": "{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vtgate_total_pods{planetscale_database_branch_id='$database_branch'})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "VTGate Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "planetscale_pods_mem_util_percentages{planetscale_database_branch_id='$database_branch', planetscale_component=\"vtgate\"}",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "VTGate Pods per AZ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "planetscale_vtgate_total_pods{planetscale_database_branch_id='$database_branch'}",
     "legendFormat": "{{planetscale_cell}}"
    }
   ]
  },
  { "title": "VTGate Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Request Rate by VTGate Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_vtgate_queries_duration_count{planetscale_database_branch_id='$database_branch'}[$__rate_interval])) by (planetscale_pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VTGate P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(planetscale_vtgate_queries_duration_bucket{planetscale_database_branch_id='$database_branch'}[$__rate_interval])) by (planetscale_pod, le))",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "VTGate P99.9",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(irate(planetscale_vtgate_queries_duration_bucket{planetscale_database_branch_id='$database_branch'}[$__rate_interval])) by (planetscale_pod, le))",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Rows Returned by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_vtgate_returned_rows_count{planetscale_database_branch_id='$database_branch'}[$__rate_interval])) by (planetscale_pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Rows Affected/Written by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_vtgate_affected_rows_count{planetscale_database_branch_id='$database_branch'}[$__rate_interval])) by (planetscale_pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Keyspace Highlights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Requests (by Keyspace, Shard and Tablet)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(irate(planetscale_vttablet_queries_count{planetscale_database_branch_id=\"$database_branch\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace, planetscale_shard, planetscale_tablet_type)",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}}@{{planetscale_tablet_type}}"
    }
   ]
  },
  {
   "title": "VTTablet P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by(planetscale_pod, planetscale_keyspace, planetscale_tablet_type, planetscale_shard, le)(\n    irate(\n      planetscale_vttablet_queries_duration_bucket{\n        planetscale_database_branch_id=~'$database_branch'\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}}@{{planetscale_tablet_type}} - {{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "VTTablet P99.9",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.999,\n  sum by(planetscale_pod, planetscale_keyspace, planetscale_tablet_type, planetscale_shard, le)(\n    irate(\n      planetscale_vttablet_queries_duration_bucket{\n        planetscale_database_branch_id=~'$database_branch'\n      }[$__rate_interval]\n    )\n  )\n)\n",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}}@{{planetscale_tablet_type}} - {{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Total Rows Affected/Written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(irate(planetscale_vttablet_queries_affected_rows_total{planetscale_database_branch_id=\"$database_branch\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace, planetscale_shard, planetscale_tablet_type, planetscale_pod)",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}}@{{planetscale_tablet_type}} - {{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "InnoDB Rows Read (by Keyspace and Tablet Type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_vttablet_queries_read_rows_total{planetscale_database_branch_id=\"$database_branch\", planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace, planetscale_tablet_type)",
     "legendFormat": "{{planetscale_keyspace}}@{{planetscale_tablet_type}}"
    }
   ]
  },
  {
   "title": "InnoDB Row Operations by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_mysql_innodb_row_operations_count{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_mysql_operation_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table Size by Shard and Table",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(planetscale_vttablet_table_storage_bytes{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_table)",
     "legendFormat": "{{planetscale_keyspace}} - {{planetscale_table}}"
    }
   ]
  },
  {
   "title": "Data size by Keyspace and Shard",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(planetscale_vttablet_table_storage_bytes{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_shard)",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}}"
    }
   ]
  },
  {
   "title": "Disk Usage by Pod",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(planetscale_vttablet_volume_capacity_bytes{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'} - planetscale_vttablet_volume_available_bytes{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) /planetscale_vttablet_volume_capacity_bytes{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}}@{{planetscale_tablet_type}}"
    }
   ]
  },
  {
   "title": "Successful VTOrc Recoveries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_vtorc_successful_recoveries_count{planetscale_database_branch_id='$database_branch'}[$__rate_interval]) != 0) by (planetscale_vtorc_recovery_type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(planetscale_vtorc_successful_recoveries_count{planetscale_database_branch_id='$database_branch'}[$__rate_interval]) != 0) by (planetscale_vtorc_recovery_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "VReplication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "max(planetscale_workflow_vreplication_lag{planetscale_database_branch_id='$database_branch'}) by (planetscale_keyspace, planetscale_source_keyspace, planetscale_source_shard, planetscale_shard, planetscale_workflow) < 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(planetscale_vttablet_replication_lag{planetscale_database_branch_id='$database_branch', planetscale_tablet_type=~\"(rdonly|replica)\"}) by (planetscale_pod, planetscale_shard, planetscale_keyspace, planetscale_tablet_type)",
     "legendFormat": "{{planetscale_keyspace}}/{{planetscale_shard}}@{{planetscale_tablet_type}} - {{planetscale_pod}}"
    }
   ]
  },
  { "title": "Connection Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Found Rows Pool",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "sum(planetscale_vttablet_found_rows_pool_capacity{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "capacity: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_found_rows_pool_active{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "active: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_found_rows_pool_in_use{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "in use: {{planetscale_keyspace}}/{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Stream Rows Pool",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 99 },
   "targets": [
    {
     "expr": "sum(planetscale_vttablet_stream_connection_pool_capacity{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "capacity: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_stream_connection_pool_active{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "active: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_stream_connection_pool_in_use{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "in use: {{planetscale_keyspace}}/{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Conn Get by Pool",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum (rate(planetscale_vttablet_connection_pool_get_count{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace)",
     "legendFormat": "Conn: {{planetscale_keyspace}}"
    },
    {
     "expr": "sum (rate(planetscale_vttablet_transaction_pool_get_count{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace)",
     "legendFormat": "Transaction: {{planetscale_keyspace}}"
    },
    {
     "expr": "sum (rate(planetscale_vttablet_found_rows_pool_get_count{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace)",
     "legendFormat": "Found Rows: {{planetscale_keyspace}}"
    },
    {
     "expr": "sum (rate(planetscale_vttablet_stream_connection_pool_get_count{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}[$__rate_interval])) by (planetscale_keyspace)",
     "legendFormat": "Stream: {{planetscale_keyspace}}"
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(planetscale_vttablet_connection_pool_capacity{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "capacity: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_connection_pool_active{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "active: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_connection_pool_in_use{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "in use: {{planetscale_keyspace}}/{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 9, "y": 111 },
   "targets": [
    {
     "expr": "sum(planetscale_vttablet_transaction_pool_capacity{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "capacity: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_transaction_pool_active{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "active: {{planetscale_keyspace}}/{{planetscale_pod}}"
    },
    {
     "expr": "sum(planetscale_vttablet_transaction_pool_in_use{planetscale_database_branch_id='$database_branch', planetscale_keyspace=~'$planetscale_keyspace', planetscale_shard=~'$planetscale_shard'}) by (planetscale_keyspace, planetscale_pod, planetscale_tablet_type)",
     "legendFormat": "in use: {{planetscale_keyspace}}/{{planetscale_pod}}"
    }
   ]
  }
 ]
}