{
 "title": "Postgres Branch Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "planetscale_database_name",
    "label": "Database",
    "query": {
     "query": "label_values(planetscale_postgres_connection_state, planetscale_database_name)"
    }
   },
   {
    "name": "database_branch",
    "label": "Branch",
    "query": {
     "query": "label_values(planetscale_postgres_connection_state{planetscale_database_name=~\"$planetscale_database_name\"}, planetscale_database_branch_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Branch Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions per Second (Commits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_postgres_database_xact_commit_total{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}[$__rate_interval])) by (planetscale_database_name)",
     "legendFormat": "{{planetscale_database_name}}"
    }
   ]
  },
  {
   "title": "Replica Lag Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(planetscale_postgres_replica_lag_seconds{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}) by (planetscale_role)",
     "legendFormat": "{{planetscale_role}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(planetscale_postgres_connection_state{planetscale_connection_state=\"active\", planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}) by (planetscale_database_name)",
     "legendFormat": "{{planetscale_database_name}}"
    }
   ]
  },
  { "title": "Resource Usage - Primaries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Connection Utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum(planetscale_postgres_connection_state{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}) / sum(planetscale_postgres_settings_max_connections{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"})",
     "legendFormat": "utilization"
    }
   ]
  },
  {
   "title": "Edge Active Connections (Global)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(planetscale_edge_active_connections{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"})",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Session States",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "sum by(planetscale_connection_state)(planetscale_postgres_connection_state{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"})",
     "legendFormat": "{{planetscale_connection_state}}"
    }
   ]
  },
  {
   "title": "PgBouncer Current Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum by(planetscale_pool)(planetscale_pgbouncer_current_connections{planetscale_database_branch_id=~\"$database_branch\"})",
     "legendFormat": "{{planetscale_pool}}"
    }
   ]
  },
  {
   "title": "Connections by Role",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(planetscale_role)(planetscale_postgres_connection_state{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"})",
     "legendFormat": "{{planetscale_role}}"
    }
   ]
  },
  {
   "title": "Connections by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum by(planetscale_cell)(planetscale_postgres_connection_state{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"})",
     "legendFormat": "{{planetscale_cell}}"
    }
   ]
  },
  { "title": "WAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "WAL Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "planetscale_postgres_wal_size_bytes{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}",
     "legendFormat": "{{planetscale_database_name}}"
    }
   ]
  },
  {
   "title": "WAL Archiver Success vs Fail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_postgres_wal_archiver_succeeded_count{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}[$__rate_interval])) by (planetscale_database_name)",
     "legendFormat": "{{planetscale_database_name}} succeeded"
    },
    {
     "expr": "sum(rate(planetscale_postgres_wal_archiver_failed_count{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}[$__rate_interval])) by (planetscale_database_name)",
     "legendFormat": "{{planetscale_database_name}} failed"
    }
   ]
  },
  {
   "title": "Max WAL Size Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "planetscale_postgres_settings_max_wal_size_bytes{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}",
     "legendFormat": "{{planetscale_database_name}}"
    }
   ]
  },
  {
   "title": "WAL Archiver Last Age Succeeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "planetscale_postgres_wal_archiver_last_age_succeeded{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}",
     "legendFormat": "{{planetscale_database_name}}"
    }
   ]
  },
  {
   "title": "Primary CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (planetscale_pod)(planetscale_pods_cpu_util_percentages{planetscale_database_branch_id=~\"$database_branch\", planetscale_component=\"hzinstance\", planetscale_role=\"primary\"})",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Primary Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (planetscale_pod)(planetscale_pods_mem_util_percentages{planetscale_database_branch_id=~\"$database_branch\", planetscale_component=\"hzinstance\", planetscale_role=\"primary\"})",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Primary IOPS Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (planetscale_pod)(rate(planetscale_pods_iops_total{planetscale_database_branch_id=~\"$database_branch\", planetscale_component=\"hzinstance\", planetscale_role=\"primary\"}[$__rate_interval]))",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  { "title": "Resource Usage - Replicas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Replica CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (planetscale_pod)(planetscale_pods_cpu_util_percentages{planetscale_database_branch_id=~\"$database_branch\", planetscale_component=\"hzinstance\", planetscale_role=\"replica\"})",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Replica Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (planetscale_pod)(planetscale_pods_mem_util_percentages{planetscale_database_branch_id=~\"$database_branch\", planetscale_component=\"hzinstance\", planetscale_role=\"replica\"})",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  {
   "title": "Replica IOPS Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum by (planetscale_pod)(rate(planetscale_pods_iops_total{planetscale_database_branch_id=~\"$database_branch\", planetscale_component=\"hzinstance\", planetscale_role=\"replica\"}[$__rate_interval]))",
     "legendFormat": "{{planetscale_pod}}"
    }
   ]
  },
  { "title": "Connections & Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  { "title": "Edge Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Edge Active Connections by Cell",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum by(planetscale_cell)(planetscale_edge_postgres_active_connections{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"})",
     "legendFormat": "{{planetscale_cell}}"
    }
   ]
  },
  {
   "title": "Edge Connection Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_edge_postgres_connection_drops_total{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}[$__rate_interval])) by (planetscale_database_name)",
     "legendFormat": "{{planetscale_database_name}} drops"
    }
   ]
  },
  {
   "title": "Edge Connection Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_edge_postgres_connection_errors_total{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}[$__rate_interval])) by (planetscale_database_name)",
     "legendFormat": "{{planetscale_database_name}}"
    }
   ]
  },
  {
   "title": "Edge Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(planetscale_edge_postgres_bytes_sent_total{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}[$__rate_interval]))",
     "legendFormat": "bytes sent"
    },
    {
     "expr": "sum(rate(planetscale_edge_postgres_bytes_received_total{planetscale_database_branch_id=~\"$database_branch\", planetscale_database_name=~\"$planetscale_database_name\"}[$__rate_interval]))",
     "legendFormat": "bytes received"
    }
   ]
  },
  { "title": "PgBouncer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "PgBouncer CPU Util per Peer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "planetscale_pgbouncer_cpu_util_per_peer_percentages{planetscale_database_branch_id=~\"$database_branch\"}",
     "legendFormat": "{{planetscale_peer}}"
    }
   ]
  },
  {
   "title": "PgBouncer Client Max Wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(planetscale_pool)(planetscale_pgbouncer_pools_client_maxwait_seconds{planetscale_database_branch_id=~\"$database_branch\"})",
     "legendFormat": "{{planetscale_pool}}"
    }
   ]
  },
  {
   "title": "PgBouncer Pool Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "targets": [
    {
     "expr": "sum by(planetscale_pool)(planetscale_pgbouncer_pools_client{planetscale_database_branch_id=~\"$database_branch\"})",
     "legendFormat": "{{planetscale_pool}} client"
    },
    {
     "expr": "sum by(planetscale_pool)(planetscale_pgbouncer_pools_server{planetscale_database_branch_id=~\"$database_branch\"})",
     "legendFormat": "{{planetscale_pool}} server"
    }
   ]
  },
  {
   "title": "PgBouncer Client Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "sum(planetscale_pgbouncer_settings_max_client_conn{planetscale_database_branch_id=~\"$database_branch\"})",
     "legendFormat": "max client conn"
    },
    {
     "expr": "sum(planetscale_pgbouncer_current_client_connections{planetscale_database_branch_id=~\"$database_branch\"})",
     "legendFormat": "current clients"
    }
   ]
  },
  {
   "title": "PgBouncer Total Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "planetscale_pgbouncer_total_peers{planetscale_database_branch_id=~\"$database_branch\"}",
     "legendFormat": "{{planetscale_pool}} peers"
    }
   ]
  }
 ]
}